name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/jamesgeorge007/github-activity-readme
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: 'Updated README with recent activity'
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
