# Update README.md with
#
# <!--START_SECTION:activity-->
# <!--END_SECTION:activity-->
# 
# to have the block between these tags filled with activity entries.
#

name: Update README

on:
  schedule:
    # https://jasonet.co/posts/scheduled-actions/#the-cron-syntax
    #        m h d m dw
    #- cron: '* * * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/jamesgeorge007/github-activity-readme
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: 'Updated README with recent activity'
          MAX_LINES: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
